# Generated by Django 3.0 on 2020-08-22 21:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('telefono', models.DecimalField(decimal_places=0, max_digits=12)),
                ('email', models.EmailField(max_length=200)),
                ('asunto', models.CharField(choices=[('bb', 'ballenas jorbadas'), ('ba', 'ballenas de lo frio'), ('ga', 'gallina'), ('sa', 'sapo')], max_length=2)),
                ('mensaje', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif', models.CharField(max_length=100)),
                ('posicion', models.DecimalField(decimal_places=12, max_digits=30)),
                ('idala', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tokenfirebase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=500)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('identificacion', models.DecimalField(decimal_places=0, max_digits=12)),
                ('telefono', models.DecimalField(decimal_places=0, max_digits=12)),
                ('direccion', models.CharField(max_length=100)),
                ('preguntasegu', models.CharField(max_length=100)),
                ('respuesta', models.CharField(max_length=50)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=15)),
                ('ciudad', models.CharField(max_length=30)),
                ('marca', models.CharField(max_length=100)),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('idalarma', models.CharField(max_length=20, unique=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carsapp.Persona')),
            ],
        ),
    ]
